sequenceDiagram
    actor Admin as Admin
    participant CP as Control Panel
    participant API as Backend API
    participant REPO as Division Repository
    participant DB as Database

    Admin->>CP: 1. Pilih menu divisi
    CP->>API: 2. GET Request /divisions
    API->>REPO: 3. getAllDivisions()
    REPO->>DB: 4. Query data Divisi
    DB-->>REPO: 5. Data Divisi
    REPO-->>API: 5.1 Data Divisi
    API-->>CP: 5.2 Data Divisi
    CP->>Admin: 6. Menampilkan data divisi
    Admin->>CP: 7. Klik menu "Aksi"
    CP->>Admin: 8. Menampilkan menu-menu aksi
    Admin->>CP: 9. Klik menu "Edit"
    CP->>Admin: 10. Menampilkan form edit divisi    
    Admin->>CP: 11. Input data divisi
    CP->>API: 12. PUT Request /divisions/{id}
    API->>API: 13. Validasi Input
    alt Divisi sudah ada
        API-->>CP: 13.1.1 Pesan error
        CP->>Admin: 13.1.2 Menampilkan pesan error
    else Divisi belum ada
        API->>REPO: 13.2.2 updateDivision()
        REPO->>DB: 13.2.3 Update data Divisi
        DB-->>REPO: 13.2.4 Data Divisi
        REPO-->>API: 13.2.5 Data Divisi
        API-->>CP: 13.2.6 Data Divisi
        CP->>Admin: 13.2.7 Menampilkan pesan berhasil update divisi
        CP->>Admin: 13.2.8 Redirect ke halaman divisi
    end